https://github.com/Netflix/eureka[Netflix Eureka] is a popular discovery server deployed at scale at organizations like Netflix.

Micronaut features a native non-blocking api:discovery.eureka.client.v2.EurekaClient[] as part of the `discovery-client` module that does not require any additional third-party dependencies and is built using Micronaut's support for https://docs.micronaut.io/latest/guide/index.html#clientAnnotation[Declarative HTTP Clients].

== Starting Eureka

The quickest way to start a Eureka server is to use to use https://spring.io/guides/gs/service-registration-and-discovery/#initial[Spring Boot's Eureka starters].

NOTE: As of this writing the official Docker images for Eureka are significantly out-of-date so it is recommended to create a Eureka server following the steps above.

== Auto Registering with Eureka

The process to register a Micronaut application with Eureka is very similar to with Consul, as seen in the previous section, simply add the necessary api:discovery.eureka.EurekaConfiguration[]. A minimal example can be seen below:

.Auto Registering with Eureka (application.yml)
[configuration]
----
micronaut:
  application:
    name: hello-world
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
----

== Customizing Eureka Service Registration

You can customize various aspects of registration with Eureka using the api:discovery.eureka.EurekaConfiguration[]. Notice that `EurekaConfiguration` extends api:discovery.client.DiscoveryClientConfiguration[]  which in turn extends link:{micronautapi}http/client/HttpClientConfiguration[HttpClientConfiguration] allowing you to customize the settings for the Eureka client, including read timeout, proxy configuration and so on.

.Example Eureka Configuration
[configuration]
----
eureka:
  client:
    readTimeout: 5s
    registration:
      asgName: myAsg
      countryId: 10
      vipAddress: 'myapp'
      leaseInfo:
        durationInSecs: 60
      metadata:
        foo: bar
      retry-count: 10
      retry-delay: 5s
      appname: some-app-name
      hostname: foo.example.com
      ip-addr: 1.2.3.4
      port: 9090
----

- `asgName` the auto scaling group name
- `countryId` the country id
- `vipAddress` The Eureka VIP address
- `durationInSecs` The lease information
- `metadata` arbitrary instance metadata
- `retry-count` How many times to retry
- `retry-delay` How long to wait between retries
- `appname` (optional) eureka instance application name, defaults to ${micronaut.application.name}
- `hostname` (optional) exposed eureka instance hostname, useful in docker bridged network environments
- `ip-addr` (optional) exposed eureka instance ip address, useful in docker bridged network environments
- `port` (optional) exposed eureka instance port, useful in docker bridged network environments

== Eureka Basic Authentication

You can customize the Eureka credentials in the URI you specify to in `defaultZone`.

For example:

.Auto Registering with Eureka
[configuration]
----
eureka:
  client:
    defaultZone: "https://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761"
----

The above example externalizes configuration of the username and password Eureka to environment variables called `EUREKA_USERNAME` and `EUREKA_PASSWORD`.

== Eureka Health Checks

Like Consul, the api:discovery.eureka.registration.EurekaAutoRegistration[] will send link:{micronautapi}health/HeartbeatEvent[HeartbeatEvent] instances with the link:{micronautapi}health/HealthStatus[HealthStatus] of the Micronaut application to Eureka.

The link:{micronautapi}management/health/monitor/HealthMonitorTask[HealthMonitorTask] will by default continuously monitor the link:{micronautapi}health/HealthStatus[HealthStatus] of the application by running health checks and the link:{micronautapi}health/CurrentHealthStatus[CurrentHealthStatus] will be sent to Eureka.

== Secure Communication with Eureka

If you wish to configure HTTPS and have clients discovery Eureka instances and communicate over HTTPS then you should set the `eureka.client.discovery.use-secure-port` option to `true` to ensure that service communication happens over HTTPS and also configure https://docs.micronaut.io/latest/guide/index.html#https[HTTPS] appropriately for each instance.
