https://github.com/spring-cloud/spring-cloud-config[Spring Cloud Config Server] Spring Cloud Config provides server-side and client-side support for externalized configuration in a distributed system. With the Config Server, you have a central place to manage external properties for applications across all environments.

A Micronaut application can be a Spring Cloud Config client to consume Spring Cloud Config Server configurations.

== Setup

The quickest way to start a Spring Cloud Config Server is to use to use https://github.com/spring-cloud/spring-cloud-config#quick-start[Spring Boot's Quick Start].

== Loading configurations from config server

The process to consume configurations in a Micronaut application from a Spring Cloud Config Server is very strait forward, simply add the necessary configurations. A complete example can be seen below:

.Registering your application as a Spring Cloud Config client  (application.yml)
[source,yaml]
----
micronaut:
  application:
    name: hello-world
  config-client:
    enabled: true
spring:
  cloud:
    config:
      enabled: true
      uri: "http://configserver:9000"
      name: filename1,filename2

----

The field name is optional, if it's not informed, the value in micronaut.application.name will be used.