pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("io.micronaut.build.shared.settings") version "8.0.0-M17"
}

rootProject.name = 'discovery-client-parent'

include 'discovery-client-bom'
include 'discovery-client'
include 'discovery-client-tests'
include 'test-suite-spring-cloud-config-server'
include 'test-suite-consul-graal'
include 'test-suite-consul-graal-serde'
include 'test-suite-consul-graal-jacksondatabind'
include 'test-suite-consul-watch'
include 'test-suite-consul-utils'

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-reactor")
    importMicronautCatalog("micronaut-validation")
}
