[versions]
# Micronaut
micronaut-docs = "2.0.0"


[libraries]
# Micronaut
micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }

testcontainers-spock = { module = 'org.testcontainers:spock' }
