[versions]
# Micronaut
micronaut = "4.1.8"
micronaut-platform = "4.1.3"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.2"
micronaut-serde = "2.2.5"
micronaut-validation = "4.0.3"
micronaut-logging = "1.1.2"

groovy = "4.0.13"
spock = "2.3-groovy-4.0"
testcontainers = "1.19.1"
awaitility = "4.2.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# Micronaut
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

spock = { module = 'org.spockframework:spock-core', version.ref = "spock" }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = "testcontainers" }
testcontainers-vault = { module = 'org.testcontainers:vault', version.ref = "testcontainers" }
