[versions]
# Micronaut
micronaut = "4.0.0-M2"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-M2"
micronaut-serde = "2.0.0-M3"
micronaut-validation = "4.0.0-M4"

groovy = "4.0.11"
spock = "2.3-groovy-4.0"
testcontainers = "1.18.0"
awaitility = "4.2.0"

[libraries]
# Micronaut
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

spock = { module = 'org.spockframework:spock-core', version.ref = "spock" }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = "testcontainers" }
testcontainers-vault = { module = 'org.testcontainers:vault', version.ref = "testcontainers" }
