[versions]
# Micronaut
micronaut = "5.0.0-M6"
micronaut-platform = "4.10.6"
micronaut-serde = "3.0.0-M1"
micronaut-reactor = "4.0.0-M1"
micronaut-test-resources="3.0.0-M1"
micronaut-validation = "5.0.0-M1"

commons-lang3 = "3.17.0"
jsonassert = "1.5.3"
awaitility = "4.3.0"
sonatype-scan = "3.1.4"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# Micronaut
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-test-resources = { module = "io.micronaut.testresources:micronaut-test-resources-bom", version.ref = "micronaut-test-resources" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert"}

testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter"}
testcontainers-consul = { module = "org.testcontainers:testcontainers-consul" }

junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine" }
