[versions]
# Micronaut
micronaut = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.6"
spock = "2.3-groovy-4.0"
testcontainers = "1.17.6"

[libraries]
# Micronaut
micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }

testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = "testcontainers" }
